package com.qburst.eshop.pojo;
// default package
// Generated 28 Mar, 2012 5:23:06 PM by Hibernate Tools 3.4.0.CR1
/**
 * Product generated by hbm2java
 */


public class Product   {


    private Integer id;
    private String catagory;
    private String name;
    private int price;
    private String comments;
    private String vendor;
    private byte[] image;

   public Product() {
   }

	
   public Product(String catagory, String name, int price, String comments, String vendor) {
       this.catagory = catagory;
       this.name = name;
       this.price = price;
       this.comments = comments;
       this.vendor = vendor;
   }
   public Product(String catagory, String name, int price, String comments, String vendor, byte[] image) {
      this.catagory = catagory;
      this.name = name;
      this.price = price;
      this.comments = comments;
      this.vendor = vendor;
      this.image = image;
   }
  
   public Integer getId() {
       return this.id;
   }
   
   public void setId(Integer id) {
       this.id = id;
   }
   public String getCatagory() {
       return this.catagory;
   }
   
   public void setCatagory(String catagory) {
       this.catagory = catagory;
   }
   public String getName() {
       return this.name;
   }
   
   public void setName(String name) {
       this.name = name;
   }
   public int getPrice() {
       return this.price;
   }
   
   public void setPrice(int price) {
       this.price = price;
   }
   public String getComments() {
       return this.comments;
   }
   
   public void setComments(String comments) {
       this.comments = comments;
   }
   public String getVendor() {
       return this.vendor;
   }
   
   public void setVendor(String vendor) {
       this.vendor = vendor;
   }
   public byte[] getImage() {
       return this.image;
   }
   
   public void setImage(byte[] image) {
       this.image = image;
   }

}